### 2.1 数据操作

* 张量（tensor）：n维数组。相当于`numpy`中的`ndarray`。
    
    * 深度学习框架中的张量相比于`numpy`来说：能够支持GPU并行计算；能够自动微分。

#### 1. 基本操作

In [4]:
# 使用pytorch
import torch


张量表示一个由多个数值组成的数组，而这个数组可以是多维度的，一维的张量对应数学上的*向量*，二维的张量对应数学上的*矩阵*，二维以上的无特殊表示。

In [6]:
# 使用arange创建一个行向量
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

轴：行0，列1

In [8]:
# 访问张量的形状（每个轴的长度）
x.shape

torch.Size([12])

In [10]:
# 张量中元素的总数
x.numel()

12

In [11]:
# 改变一个张量的形状，而不改变元素个数和数值
X = x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [14]:
# 通过调用-1来代替上述的改变形状
X1 = x.reshape(-1,4)
X1


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [15]:

X2 = x.reshape(3,-1)
X2

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [16]:
# 初始化一个全为0的张量
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [17]:
# 初始化一个全为1 的张量
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [18]:
# 从均值为0标准差为1的 标准高斯（正态分布）中随机采样
torch.randn(3,4)


tensor([[ 0.7291, -0.8580, -0.5570,  0.0374],
        [ 2.0765,  1.2677,  0.0759,  0.0580],
        [-1.1753, -1.4308, -1.7913, -0.6926]])

In [21]:
# 可用所提供的的python列表将其转化为tensor
# 这里最外层对应轴0（3），最内层对应轴1（4）
torch.tensor([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

#### 2. 运算符

In [22]:
# 按元素操作 + - * / **
x = torch.tensor([0.2, 1, 3])
y = torch.tensor([2, 2, 2])

x + y, x - y, x * y, x / y, x ** y


(tensor([2.2000, 3.0000, 5.0000]),
 tensor([-1.8000, -1.0000,  1.0000]),
 tensor([0.4000, 2.0000, 6.0000]),
 tensor([0.1000, 0.5000, 1.5000]),
 tensor([0.0400, 1.0000, 9.0000]))

In [23]:
torch.exp(x)

tensor([ 1.2214,  2.7183, 20.0855])

In [27]:
# 可以把多个张量联结（concatenate）在一起，
# 让他们端对端的形成一个更大的张量
# 只需提供张量列表，并给出沿那个轴联结
X = torch.arange(12, dtype=torch.float32).reshape(3,4)
Y = torch.tensor([[1.0, 2.0, 3, 4], [4, 5, 2, 1], [6, 4, 7 ,3]])

# 按照行来联结(追加行), 按照列来联结(追加列)
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  5.,  2.,  1.],
         [ 6.,  4.,  7.,  3.]]),
 tensor([[ 0.,  1.,  2.,  3.,  1.,  2.,  3.,  4.],
         [ 4.,  5.,  6.,  7.,  4.,  5.,  2.,  1.],
         [ 8.,  9., 10., 11.,  6.,  4.,  7.,  3.]]))

In [28]:
# 通过逻辑运算符来构建二元张量
X == Y

tensor([[False, False, False, False],
        [ True,  True, False, False],
        [False, False, False, False]])

In [29]:
X > Y

tensor([[False, False, False, False],
        [False, False,  True,  True],
        [ True,  True,  True,  True]])

In [30]:
X < Y

tensor([[ True,  True,  True,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [31]:
# 对张量中的所有元素求和，会产生一个单元素张量
X.sum()

tensor(66.)

In [32]:
Y.sum()

tensor(42.)

#### 3. 广播机制

在某些情况下，即使张量的形状不同，可以利用**广播机制（broadcasting mechanism）**来执行按元素操作。

1. 通过复制一个或者两个数组来保持张量的形状一致；
2. 然后再对他们进行按元素运算。

In [33]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))

a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [34]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

上述过程描述为：

$$a = 
\begin{pmatrix}
0\\
1\\
2\\
\end{pmatrix}
$$

$$b = 
\begin{pmatrix}
0 & 1
\end{pmatrix}
$$

1. `a`张量按照`b`张量的形状复制一列：

$$a^` = 
\begin{pmatrix}
0 & 0\\
1 & 1\\
2 & 2\\
\end{pmatrix}
$$

得到一个形状为`3*2`的张量。

2. `b`同理也按照`a`张量的形状复制两行：

$$b^` = 
\begin{pmatrix}
0 & 1\\
0 & 1\\
0 & 1\\
\end{pmatrix}
$$

同样得到一个形状为`3*2`的张量。

3. 然后两个张量按照元素相加即可：

$$a + b = 
\begin{pmatrix}
0 & 0\\
1 & 1\\
2 & 2\\
\end{pmatrix}
+
\begin{pmatrix}
0 & 1\\
0 & 1\\
0 & 1\\
\end{pmatrix}
=
\begin{pmatrix}
0 & 1\\
1 & 2\\
2 & 3\\
\end{pmatrix}
$$

若张量为三维以上：

In [105]:
# 三维张量测试
X_3 = torch.tensor([[[0, 1]], [[0, 1]]])
X_3, X_3.shape

(tensor([[[0, 1]],
 
         [[0, 1]]]),
 torch.Size([2, 1, 2]))

In [106]:
Y_3 = torch.tensor([[[0], [1]]])
Y_3, Y_3.shape

(tensor([[[0],
          [1]]]),
 torch.Size([1, 2, 1]))

In [107]:
XY = X_3 + Y_3
XY, XY.shape

(tensor([[[0, 1],
          [1, 2]],
 
         [[0, 1],
          [1, 2]]]),
 torch.Size([2, 2, 2]))

#### 4. 索引和切片

In [35]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [36]:
# 选择X中最后一个元素
X[-1]

tensor([ 8.,  9., 10., 11.])

In [38]:
# 选择X中第2到3个元素
X[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [40]:
# 指定索引将元素写入张量
X[1,2] = 0.2
X

tensor([[ 0.0000,  1.0000,  2.0000,  3.0000],
        [ 4.0000,  5.0000,  0.2000,  7.0000],
        [ 8.0000,  9.0000, 10.0000, 11.0000]])

In [41]:
# 为多个元素赋值相同的值
X[0:2, :] = 5
X

tensor([[ 5.,  5.,  5.,  5.],
        [ 5.,  5.,  5.,  5.],
        [ 8.,  9., 10., 11.]])

#### 5. 节省内存

运行一些操作可能会导致为新的结果分配新的内存，如不及时释放，会占用过多内存，导致运行出错。

在机器学习中，会有数以百兆的参数，一般会希望这些参数原地更新，如果不及时更新，那么其他引用可能会指向旧的内存地址的参数，这样参数可能会错误的引用旧的参数。

In [44]:
# PYTHON中的id（）可以提供内存中引用对象的确切位置
before = id(Y)
Y = X + Y
after = id(Y)
before == after

False

执行原地操作，可以使用切片表示法将操作结果分配给先前分配的数组。

如果在后续计算中没有重复使用X， 我们也可以使用X[:] = X + Y或X += Y来减少操作的内存开销。

In [47]:
# 新建一个变量Z来说明
Z = torch.zeros_like(Y)

before = id(Z)

Z[:] = X + Y

before, id(Z)

(140459270943104, 140459270943104)

In [48]:
# 如果X变量后面不再使用
before = id(X)
X += Y

before, id(X)

(140459270555456, 140459270555456)

In [49]:
# 如果X变量后面不再使用
before = id(X)

X[:] = X + Y

before, id(X)

(140459270555456, 140459270555456)

#### 6. 转换为其他python格式

* pytorch中的张量（tensor）和numpy中的张量（ndarray）可以互转；

* 他们会共享底层的内存，就地操作更改一个张量会引起另一个张量的改变。

In [50]:
A = X.numpy()
id(A)

140459271438224

In [51]:
B = torch.tensor(A)
id(B)

140459270952320

In [64]:
# 就地修改张量X 会修改到A
X += Y

In [73]:
X, id(X)

(tensor([[103., 109., 115., 121.],
         [121., 127., 109., 103.],
         [190., 197., 234., 229.]]),
 140459270555456)

In [74]:
A, id(A)

(array([[103., 109., 115., 121.],
        [121., 127., 109., 103.],
        [190., 197., 234., 229.]], dtype=float32),
 140459271438224)

In [77]:
# 原地修改A X 也会对应的改变
A += 1
A

array([[105., 111., 117., 123.],
       [123., 129., 111., 105.],
       [192., 199., 236., 231.]], dtype=float32)

In [78]:
X

tensor([[105., 111., 117., 123.],
        [123., 129., 111., 105.],
        [192., 199., 236., 231.]])

**以上同时改变的性质仅针对于从torch的张量转换为numpy的张量，若初始化一个numpy张量，并转换为一个torch张量，不具有同时改变的性质，他们并未共享同一底层内存。**

In [83]:
# 定义一个 2*3的numpy张量
C = np.ndarray([2,3])

In [84]:
C

array([[1.31941413e+14, 3.87028163e+14, 5.98134466e+14],
       [7.91648547e+13, 1.29478512e+16, 5.17914048e+16]])

In [85]:
D = torch.tensor(C)

In [86]:
D

tensor([[1.3194e+14, 3.8703e+14, 5.9813e+14],
        [7.9165e+13, 1.2948e+16, 5.1791e+16]], dtype=torch.float64)

In [89]:
C += C
C

array([[2.63882826e+14, 7.74056326e+14, 1.19626893e+15],
       [1.58329709e+14, 2.58957024e+16, 1.03582810e+17]])

In [90]:
D

tensor([[1.3194e+14, 3.8703e+14, 5.9813e+14],
        [7.9165e+13, 1.2948e+16, 5.1791e+16]], dtype=torch.float64)

In [92]:
D += C
D

tensor([[3.9582e+14, 1.1611e+15, 1.7944e+15],
        [2.3749e+14, 3.8844e+16, 1.5537e+17]], dtype=torch.float64)

In [93]:
C

array([[2.63882826e+14, 7.74056326e+14, 1.19626893e+15],
       [1.58329709e+14, 2.58957024e+16, 1.03582810e+17]])

要将大小为1的张量转换为标量，可以使用`item`函数和`python`的内置函数：


In [ ]:
a = torch.tensor([1.5])

a, a.item(), float(a), int(a)

### 2.2 数据预处理

主要利用`pandas`对数据进行预处理，并转换为张量。

#### 1. 读取数据集

创建一个人工数据集，并将其存为`csv`格式。

In [113]:
import os

os.makedirs(os.path.join('.', 'data'), exist_ok=True)
data_file = os.path.join('.', 'data', 'house_tiny.csv')

with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')    # 列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')