### 2.1 数据操作

* 张量（tensor）：n维数组。相当于`numpy`中的`ndarray`。
    
    * 深度学习框架中的张量相比于`numpy`来说：能够支持GPU并行计算；能够自动微分。

#### 1. 基本操作

In [4]:
# 使用pytorch
import torch


张量表示一个由多个数值组成的数组，而这个数组可以是多维度的，一维的张量对应数学上的*向量*，二维的张量对应数学上的*矩阵*，二维以上的无特殊表示。

In [6]:
# 使用arange创建一个行向量
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

轴：行0，列1

In [8]:
# 访问张量的形状（每个轴的长度）
x.shape

torch.Size([12])

In [10]:
# 张量中元素的总数
x.numel()

12

In [11]:
# 改变一个张量的形状，而不改变元素个数和数值
X = x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [14]:
# 通过调用-1来代替上述的改变形状
X1 = x.reshape(-1,4)
X1


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [15]:

X2 = x.reshape(3,-1)
X2

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [16]:
# 初始化一个全为0的张量
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [17]:
# 初始化一个全为1 的张量
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [18]:
# 从均值为0标准差为1的 标准高斯（正态分布）中随机采样
torch.randn(3,4)


tensor([[ 0.7291, -0.8580, -0.5570,  0.0374],
        [ 2.0765,  1.2677,  0.0759,  0.0580],
        [-1.1753, -1.4308, -1.7913, -0.6926]])

In [21]:
# 可用所提供的的python列表将其转化为tensor
# 这里最外层对应轴0（3），最内层对应轴1（4）
torch.tensor([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

#### 2. 运算符

In [22]:
# 按元素操作 + - * / **
x = torch.tensor([0.2, 1, 3])
y = torch.tensor([2, 2, 2])

x + y, x - y, x * y, x / y, x ** y


(tensor([2.2000, 3.0000, 5.0000]),
 tensor([-1.8000, -1.0000,  1.0000]),
 tensor([0.4000, 2.0000, 6.0000]),
 tensor([0.1000, 0.5000, 1.5000]),
 tensor([0.0400, 1.0000, 9.0000]))

In [23]:
torch.exp(x)

tensor([ 1.2214,  2.7183, 20.0855])

In [27]:
# 可以把多个张量联结（concatenate）在一起，
# 让他们端对端的形成一个更大的张量
# 只需提供张量列表，并给出沿那个轴联结
X = torch.arange(12, dtype=torch.float32).reshape(3,4)
Y = torch.tensor([[1.0, 2.0, 3, 4], [4, 5, 2, 1], [6, 4, 7 ,3]])

# 按照行来联结(追加行), 按照列来联结(追加列)
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  5.,  2.,  1.],
         [ 6.,  4.,  7.,  3.]]),
 tensor([[ 0.,  1.,  2.,  3.,  1.,  2.,  3.,  4.],
         [ 4.,  5.,  6.,  7.,  4.,  5.,  2.,  1.],
         [ 8.,  9., 10., 11.,  6.,  4.,  7.,  3.]]))

In [28]:
# 通过逻辑运算符来构建二元张量
X == Y

tensor([[False, False, False, False],
        [ True,  True, False, False],
        [False, False, False, False]])

In [29]:
X > Y

tensor([[False, False, False, False],
        [False, False,  True,  True],
        [ True,  True,  True,  True]])

In [30]:
X < Y

tensor([[ True,  True,  True,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [31]:
# 对张量中的所有元素求和，会产生一个单元素张量
X.sum()

tensor(66.)

In [32]:
Y.sum()

tensor(42.)

#### 3. 广播机制

在某些情况下，即使张量的形状不同，可以利用**广播机制（broadcasting mechanism）**来执行按元素操作。

1. 通过复制一个或者两个数组来保持张量的形状一致；
2. 然后再对他们进行按元素运算。

In [33]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))

a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [34]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

上述过程描述为：

$$a = 
\begin{pmatrix}
0\\
1\\
2\\
\end{pmatrix}
$$

$$b = 
\begin{pmatrix}
0 & 1
\end{pmatrix}
$$

1. `a`张量按照`b`张量的形状复制一列：

$$a^` = 
\begin{pmatrix}
0 & 0\\
1 & 1\\
2 & 2\\
\end{pmatrix}
$$

得到一个形状为`3*2`的张量。

2. `b`同理也按照`a`张量的形状复制两行：

$$b^` = 
\begin{pmatrix}
0 & 1\\
0 & 1\\
0 & 1\\
\end{pmatrix}
$$

同样得到一个形状为`3*2`的张量。

3. 然后两个张量按照元素相加即可：

$$a + b = 
\begin{pmatrix}
0 & 0\\
1 & 1\\
2 & 2\\
\end{pmatrix}
+
\begin{pmatrix}
0 & 1\\
0 & 1\\
0 & 1\\
\end{pmatrix}
=
\begin{pmatrix}
0 & 1\\
1 & 2\\
2 & 3\\
\end{pmatrix}
$$

#### 4. 索引和切片

In [35]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [36]:
# 选择X中最后一个元素
X[-1]

tensor([ 8.,  9., 10., 11.])

In [38]:
# 选择X中第2到3个元素
X[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [40]:
# 指定索引将元素写入张量
X[1,2] = 0.2
X

tensor([[ 0.0000,  1.0000,  2.0000,  3.0000],
        [ 4.0000,  5.0000,  0.2000,  7.0000],
        [ 8.0000,  9.0000, 10.0000, 11.0000]])