### 2.1 数据操作

* 张量（tensor）：n维数组。相当于`numpy`中的`ndarray`。
    
    * 深度学习框架中的张量相比于`numpy`来说：能够支持GPU并行计算；能够自动微分。

#### 1. 基本操作

In [4]:
# 使用pytorch
import torch


张量表示一个由多个数值组成的数组，而这个数组可以是多维度的，一维的张量对应数学上的*向量*，二维的张量对应数学上的*矩阵*，二维以上的无特殊表示。

In [6]:
# 使用arange创建一个行向量
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

轴：行0，列1

In [8]:
# 访问张量的形状（每个轴的长度）
x.shape

torch.Size([12])

In [10]:
# 张量中元素的总数
x.numel()

12

In [11]:
# 改变一个张量的形状，而不改变元素个数和数值
X = x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [14]:
# 通过调用-1来代替上述的改变形状
X1 = x.reshape(-1,4)
X1


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [15]:

X2 = x.reshape(3,-1)
X2

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [16]:
# 初始化一个全为0的张量
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [17]:
# 初始化一个全为1 的张量
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [18]:
# 从均值为0标准差为1的 标准高斯（正态分布）中随机采样
torch.randn(3,4)


tensor([[ 0.7291, -0.8580, -0.5570,  0.0374],
        [ 2.0765,  1.2677,  0.0759,  0.0580],
        [-1.1753, -1.4308, -1.7913, -0.6926]])

In [21]:
# 可用所提供的的python列表将其转化为tensor
# 这里最外层对应轴0（3），最内层对应轴1（4）
torch.tensor([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

#### 2. 运算符

In [22]:
# 按元素操作 + - * / **
x = torch.tensor([0.2, 1, 3])
y = torch.tensor([2, 2, 2])

x + y, x - y, x * y, x / y, x ** y


(tensor([2.2000, 3.0000, 5.0000]),
 tensor([-1.8000, -1.0000,  1.0000]),
 tensor([0.4000, 2.0000, 6.0000]),
 tensor([0.1000, 0.5000, 1.5000]),
 tensor([0.0400, 1.0000, 9.0000]))

In [23]:
torch.exp(x)

tensor([ 1.2214,  2.7183, 20.0855])

In [ ]:
# 可以把多个张量联结（concatenate）在一起，
# 让他们端对端的形成一个更大的张量
# 只需提供张量列表，并给出沿那个轴联结
